### ISSUE TITLE
Suggestion: Lower java version to 8

### ISSUE THREAD

**Issue by mfnalex** [oraxen/protectionlib#22]
Is there any reason for requiring java 17? Many of my plugins still support 1.16.5, and hence are compiled for Java 8. I don't see any java features in the code that are specific to later versions, so I suggest to drop the required version in build.gradle.kts to java 8.

**Comment by Boy0000** [comment]
@mfnalex should be ill look into it

**Comment by Boy0000** [comment]
@mfnalex so PlotSquared requires java 17 thus it cannot be lowered
```kts
tasks {
    compileJava {
        options.release.set(8)
        dependsOn(clean)
    }
}
```

if you want to lower the version you can fork this, add this to the build.gradle.kts file and remove plotsquared

**Comment by mfnalex** [comment]
Yes I know that java 17 depencencies are the issues. But that doesn't mean that ProtectionLib itself has to be compiled against java 17

**Comment by mfnalex** [comment]
At least in maven, you can easily compile with target/source java 8, while still are fine to access java 17 dependencies, see my fork here for example: https://github.com/JEFF-Media-GbR/protectionlib-java8 (only cavet is ofc, is indeed requires java 17 to compile, not to run though - unless PlotSquared is also running on the server. But in that case, Java 17 is required anyway, because otherwise, PlotSuqred wouldn't run, anyway)

**Comment by Boy0000** [comment]
@mfnalex i know for a fact you are right because i recall doing this before
But that was in groovy. I'll dig through some old projects and see if i cant find it

**Comment by Boy0000** [comment]
@mfnalex if you can try using the `java_8` branch I just made
I seem to be able to compile it fine with Java 8
